name: Update Lines of Code in README

on:
  schedule:
    - cron: "0 0 * * 0" # Runs weekly
  workflow_dispatch:

jobs:
  count-lines:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq cloc

    - name: Fetch and Clone Repositories
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        USERNAME="arhamkhnz"
        REPOS=$(curl -H "Authorization: token $GH_PAT" -s "https://api.github.com/user/repos?per_page=100" | jq -r '.[].clone_url')

        mkdir -p public-repos
        cd public-repos

        for REPO in $REPOS; do
          echo "Cloning $REPO..."
          git clone "$REPO"
        done

        echo "Calculating total lines of code..."
        mkdir -p ../output
        cloc . --json > ../output/cloc-output.json

    - name: Update README.md
      run: |
        # Extract the total lines from cloc-output.json
        TOTAL_LINES=$(jq '.SUM.code' output/cloc-output.json)
        
        # Replace the placeholder in README.md
        sed -i "/<!-- lines-of-code -->/c\Total Lines of Code: $TOTAL_LINES <!-- lines-of-code -->" README.md

    - name: Stage All Changes
      run: |
        git add -A # Stages all changes, including untracked files

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git commit -m "Update total lines of code" || echo "No changes to commit"
        git push